/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.javafxtut;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;

public class App extends Application {
  @Override
  public void start(Stage stage) throws IOException {
    URL xmlResource = getClass().getResource("/ui/calc-split.xml");
    GridPane gp = FXMLLoader.load(xmlResource);
    Scene scene = new Scene(gp,640,480);
    URL cssResource = getClass().getResource("/ui/calcbuttons.css");
    scene.getStylesheets().add(cssResource.toString());
    stage.setScene(scene);
    stage.show();
  }
}
