/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.javafxtut;

import edu.duke.ece651.controller.CalculatorController;
import edu.duke.ece651.controller.NumButtonController;
import edu.duke.ece651.model.RPNStack;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.ListView;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;

public class App extends Application {
  @Override
  public void start(Stage stage) throws IOException {
    URL cssResource = getClass().getResource("/ui/calcbuttons.css");
    URL xmlResource = getClass().getResource("/ui/calc-split.xml");
    RPNStack model = new RPNStack();
    FXMLLoader loader = new FXMLLoader(xmlResource);
    HashMap<Class<?>,Object> controllers = new HashMap<>();
    controllers.put(NumButtonController.class, new NumButtonController(model));
    controllers.put(CalculatorController.class, new CalculatorController());
    loader.setControllerFactory((c)->{
      return controllers.get(c);
    });
    GridPane gp = loader.load();
    Scene scene = new Scene(gp,640,480);
    scene.getStylesheets().add(cssResource.toString());
    @SuppressWarnings("unchecked")
    ListView<Double> operands = (ListView<Double>)scene.lookup("#rpnstack");
    operands.setItems(model.getList());
    stage.setScene(scene);
    stage.show();
  }
}
